# ARG BUILD_FROM
FROM alpine

WORKDIR /app

# Install requirements for add-on
# (alpine image)
# RUN apk add --no-cache \
#    python3 bluez py-pip git

RUN apk add --no-cache \
    python3 py-pip git \
    && apk add --no-cache bluez #< 5.66-r4

# Copy data for add-on
COPY run.sh run.sh
COPY main.py main.py
COPY requirements.txt requirements.txt
COPY . .

RUN pip3 install -r requirements.txt \
&& chmod a+x run.sh

CMD [ "./run.sh" ]